### ISSUE TITLE
Add checks for some common mistakes

### ISSUE THREAD

**Issue by rahul286** [rtlearn/php-starter#2]
I am not sure which of these will be possible in the PR workflow

- [x] missing readme.md (Github Classroom creates an ongoing PR from the first commit so the readme.md file will be there. If not, maybe we can create a GH issue the repo saying this repo doesn't have GH issue)
- [x] temporary files committed such as log files/backup files
- [x] build files committed such as sass files (actually student should not use CSS preprocessor or any frameworks)
- [x] credentials added inline in code. missing config file

**Comment by mrrobot47** [comment]
- [x] missing readme.md (Github Classroom creates an ongoing PR from the first commit so the readme.md file will be there. If not, maybe we can create a GH issue the repo saying this repo doesn't have GH issue)

**PR:** https://github.com/rtlearn/php-starter/pull/4

As readme will already be there, this action will check if the readme is updated or not (via git diff) in the PR. If the readme is not updated, it will fail and ask the user to update the readme with project details.

---

- [x] temporary files committed such as log files/backup files
- [x] build files committed such as sass files (actually student should not use CSS preprocessor or any frameworks)

**PR:** #5 

This action will check all the files listed in [`.github/temp-files/.gitignore`](https://github.com/rtlearn/php-starter/blob/c955e078c998cabe9469767c621b27ea46481069/.github/temp-files/.gitignore)
In case any files in PR are found that match the above file, the action will fail.

To maintain the list of files that should not be there in the repo, simply update this file [`.github/temp-files/.gitignore`](https://github.com/rtlearn/php-starter/blob/c955e078c998cabe9469767c621b27ea46481069/.github/temp-files/.gitignore).

It already contains log files, sass files checks, etc.

---

- [x] credentials added inline in code. missing config file

**PR:** #6 

Actions setup of https://github.com/zricethezav/gitleaks
It will fail if any secret, config etc. is found.
